// Real G1 race calendar (Uma Musume: Pretty Derby), sourced from GameTora's race database.
// distanceCategory maps to the same Sprint/Mile/Medium/Long/Dirt scale used for horse aptitudes.
export const G1_RACES = [
  { id: 931206, name: "American Oaks", distance: 2000, terrain: "turf", distanceCategory: "Medium" },
  { id: 102301, name: "Arima Kinen", distance: 2500, terrain: "turf", distanceCategory: "Long" },
  { id: 102201, name: "Asahi Hai Futurity Stakes", distance: 1600, terrain: "turf", distanceCategory: "Mile" },
  { id: 102001, name: "Champions Cup", distance: 1800, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 100101, name: "February Stakes", distance: 1600, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 102101, name: "Hanshin Juvenile Fillies", distance: 1600, terrain: "turf", distanceCategory: "Mile" },
  { id: 102401, name: "Hopeful Stakes", distance: 2000, terrain: "turf", distanceCategory: "Medium" },
  { id: 110501, name: "JBC Classic", distance: 2000, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 110301, name: "JBC Ladies\u2019 Classic", distance: 1800, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 110401, name: "JBC Sprint", distance: 1200, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 101901, name: "Japan Cup", distance: 2400, terrain: "turf", distanceCategory: "Medium" },
  { id: 103101, name: "Japan Cup", distance: 2200, terrain: "turf", distanceCategory: "Medium" },
  { id: 110201, name: "Japan Dirt Derby", distance: 2000, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 100901, name: "Japanese Oaks", distance: 2400, terrain: "turf", distanceCategory: "Medium" },
  { id: 110901, name: "Kashiwa Kinen", distance: 1600, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 110701, name: "Kawasaki Kinen", distance: 2100, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 101501, name: "Kikuka Sho", distance: 3000, terrain: "turf", distanceCategory: "Long" },
  { id: 111001, name: "M.C. Nambu Hai", distance: 1600, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 101801, name: "Mile Championship", distance: 1600, terrain: "turf", distanceCategory: "Mile" },
  { id: 103001, name: "Mile Championship Nambu Hai", distance: 1600, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 100701, name: "NHK Mile Cup", distance: 1600, terrain: "turf", distanceCategory: "Mile" },
  { id: 100401, name: "Oka Sho", distance: 1600, terrain: "turf", distanceCategory: "Mile" },
  { id: 100301, name: "Osaka Hai", distance: 2000, terrain: "turf", distanceCategory: "Medium" },
  { id: 120101, name: "Prix de l'Arc de Triomphe", distance: 2400, terrain: "turf", distanceCategory: "Medium" },
  { id: 103401, name: "Queen Elizabeth Cup", distance: 2200, terrain: "turf", distanceCategory: "Medium" },
  { id: 101701, name: "Queen Elizabeth II Cup", distance: 2200, terrain: "turf", distanceCategory: "Medium" },
  { id: 100501, name: "Satsuki Sho", distance: 2000, terrain: "turf", distanceCategory: "Medium" },
  { id: 101401, name: "Shuka Sho", distance: 2000, terrain: "turf", distanceCategory: "Medium" },
  { id: 101301, name: "Sprinters Stakes", distance: 1200, terrain: "turf", distanceCategory: "Sprint" },
  { id: 100201, name: "Takamatsunomiya Kinen", distance: 1200, terrain: "turf", distanceCategory: "Sprint" },
  { id: 101201, name: "Takarazuka Kinen", distance: 2200, terrain: "turf", distanceCategory: "Medium" },
  { id: 110101, name: "Teio Sho", distance: 2000, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 101601, name: "Tenno Sho (Autumn)", distance: 2000, terrain: "turf", distanceCategory: "Medium" },
  { id: 100601, name: "Tenno Sho (Spring)", distance: 3200, terrain: "turf", distanceCategory: "Long" },
  { id: 110601, name: "Tokyo Daishoten", distance: 2000, terrain: "dirt", distanceCategory: "Dirt" },
  { id: 101001, name: "Tokyo Yushun (Japanese Derby)", distance: 2400, terrain: "turf", distanceCategory: "Medium" },
  { id: 100801, name: "Victoria Mile", distance: 1600, terrain: "turf", distanceCategory: "Mile" },
  { id: 101101, name: "Yasuda Kinen", distance: 1600, terrain: "turf", distanceCategory: "Mile" },
  { id: 110801, name: "Zen-Nippon Junior Yushun", distance: 1600, terrain: "dirt", distanceCategory: "Dirt" },
]
