import { makeId } from './storage'

// Seeded from a GameTora collection export; supportId lets a future
// pasted export update these in place instead of matching by name.
export const SEED_CARDS = [
  { name: "Admire Vega [Aim for the Brightest]", type: "guts", rarity: "SR", limitBreak: 3, supportId: 20041 },
  { name: "Admire Vega [Lucky Star in the Sky]", type: "power", rarity: "SSR", limitBreak: 1, supportId: 30077 },
  { name: "Admire Vega [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10075 },
  { name: "Agnes Digital [Digital's Recharge Station]", type: "power", rarity: "SR", limitBreak: 4, supportId: 20005 },
  { name: "Agnes Digital [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10026 },
  { name: "Agnes Tachyon [Experimental Studies on Subject A]", type: "wisdom", rarity: "SR", limitBreak: 4, supportId: 20012 },
  { name: "Agnes Tachyon [Q\u22600]", type: "speed", rarity: "SSR", limitBreak: 0, supportId: 30101 },
  { name: "Agnes Tachyon [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10036 },
  { name: "Air Groove [Nothing Escapes the Vice Prez]", type: "guts", rarity: "SR", limitBreak: 4, supportId: 20004 },
  { name: "Air Groove [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10025 },
  { name: "Air Shakur [7 More Centimeters]", type: "wisdom", rarity: "SSR", limitBreak: 0, supportId: 30013 },
  { name: "Air Shakur [Mag!c Number]", type: "speed", rarity: "SSR", limitBreak: 3, supportId: 30092 },
  { name: "Air Shakur [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10037 },
  { name: "Aoi Kiryuin [Tracen Academy]", type: "friend", rarity: "R", limitBreak: 4, supportId: 10022 },
  { name: "Aoi Kiryuin [Trainers' Teamwork]", type: "friend", rarity: "SR", limitBreak: 4, supportId: 20021 },
  { name: "Bamboo Memory [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10065 },
  { name: "Biko Pegasus [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10042 },
  { name: "Biwa Hayahide [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10029 },
  { name: "Biwa Hayahide [Trial Initiation]", type: "power", rarity: "SR", limitBreak: 4, supportId: 20006 },
  { name: "Biwa Hayahide [Uchronia Architect]", type: "stamina", rarity: "SSR", limitBreak: 4, supportId: 30113 },
  { name: "Curren Chan [Cozy Cute Memory \u266a]", type: "speed", rarity: "SR", limitBreak: 4, supportId: 20044 },
  { name: "Curren Chan [Cutie Pie with Shining Eyes]", type: "wisdom", rarity: "SSR", limitBreak: 0, supportId: 30068 },
  { name: "Curren Chan [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10073 },
  { name: "Daitaku Helios [Let's Get This Party Lit!]", type: "power", rarity: "SR", limitBreak: 4, supportId: 20024 },
  { name: "Daitaku Helios [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10052 },
  { name: "Daiwa Scarlet [Mini\u2606Vacation]", type: "power", rarity: "SSR", limitBreak: 2, supportId: 30047 },
  { name: "Daiwa Scarlet [Nothing Hard Work Can't Solve!]", type: "wisdom", rarity: "SR", limitBreak: 4, supportId: 20002 },
  { name: "Daiwa Scarlet [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10023 },
  { name: "Eishin Flash [5:00 a.m.\u2014Right on Schedule]", type: "speed", rarity: "SR", limitBreak: 4, supportId: 20013 },
  { name: "Eishin Flash [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10038 },
  { name: "El Condor Pasa [Champion's Passion]", type: "power", rarity: "SSR", limitBreak: 4, supportId: 30007 },
  { name: "El Condor Pasa [Mud-Caked Compa\u00f1ero]", type: "speed", rarity: "SR", limitBreak: 0, supportId: 20033 },
  { name: "El Condor Pasa [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10011 },
  { name: "Fine Motion [Grma, Ramen \u266a]", type: "power", rarity: "SR", limitBreak: 3, supportId: 20037 },
  { name: "Fine Motion [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10028 },
  { name: "Fuji Kiseki [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10049 },
  { name: "Fuji Kiseki [Well, Look Who's Home]", type: "wisdom", rarity: "SR", limitBreak: 4, supportId: 20001 },
  { name: "Gold City [Run(my)way]", type: "speed", rarity: "SSR", limitBreak: 0, supportId: 30014 },
  { name: "Gold City [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10017 },
  { name: "Gold Ship [Breakaway Battleship]", type: "stamina", rarity: "SSR", limitBreak: 0, supportId: 30004 },
  { name: "Gold Ship [That Time I Became the Strongest]", type: "speed", rarity: "SSR", limitBreak: 3, supportId: 30057 },
  { name: "Gold Ship [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10006 },
  { name: "Grass Wonder [Fairest Fleur]", type: "guts", rarity: "SSR", limitBreak: 1, supportId: 30006 },
  { name: "Grass Wonder [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10009 },
  { name: "Haru Urara [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10020 },
  { name: "Haru Urara [Urara's Day Off!]", type: "guts", rarity: "SSR", limitBreak: 4, supportId: 30019 },
  { name: "Hishi Akebono [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10064 },
  { name: "Hishi Akebono [Who Wants the First Bite?]", type: "guts", rarity: "SSR", limitBreak: 0, supportId: 30040 },
  { name: "Hishi Amazon [Reach the Top!]", type: "power", rarity: "SR", limitBreak: 4, supportId: 20003 },
  { name: "Hishi Amazon [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10024 },
  { name: "Ikuno Dictus [Beloved Orchid Bouquet]", type: "stamina", rarity: "SSR", limitBreak: 0, supportId: 30099 },
  { name: "Ikuno Dictus [Never Skip Warm-Ups]", type: "wisdom", rarity: "SR", limitBreak: 4, supportId: 20025 },
  { name: "Ikuno Dictus [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10053 },
  { name: "Inari One [Laughing through the Mud]", type: "power", rarity: "SR", limitBreak: 0, supportId: 20032 },
  { name: "Inari One [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10068 },
  { name: "Ines Fujin [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10035 },
  { name: "Ines Fujin [Watch My Star Fly!]", type: "guts", rarity: "SSR", limitBreak: 0, supportId: 30011 },
  { name: "Ines Fujin [You Earned It!]", type: "wisdom", rarity: "SR", limitBreak: 0, supportId: 20030 },
  { name: "Kawakami Princess [Go Go\u2606Princess!]", type: "power", rarity: "SSR", limitBreak: 3, supportId: 30096 },
  { name: "Kawakami Princess [Princess Bride]", type: "speed", rarity: "SSR", limitBreak: 0, supportId: 30039 },
  { name: "Kawakami Princess [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10063 },
  { name: "King Halo [First-Rate Plan]", type: "speed", rarity: "SR", limitBreak: 4, supportId: 20020 },
  { name: "King Halo [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10048 },
  { name: "Kitasan Black [Fire at My Heels]", type: "speed", rarity: "SSR", limitBreak: 4, supportId: 30028 },
  { name: "Kitasan Black [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10055 },
  { name: "Light Hello [Event Producer]", type: "friend", rarity: "R", limitBreak: 4, supportId: 10083 },
  { name: "Light Hello [From the Ground Up]", type: "friend", rarity: "SSR", limitBreak: 0, supportId: 30052 },
  { name: "Manhattan Cafe [It's on the House]", type: "stamina", rarity: "SSR", limitBreak: 0, supportId: 30110 },
  { name: "Manhattan Cafe [My Solo Drawn to Raindrop Drums]", type: "stamina", rarity: "SR", limitBreak: 4, supportId: 20008 },
  { name: "Manhattan Cafe [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10031 },
  { name: "Maruzensky [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10004 },
  { name: "Marvelous Sunday [A Marvelous \u2606 Plan]", type: "wisdom", rarity: "SR", limitBreak: 4, supportId: 20015 },
  { name: "Marvelous Sunday [Dazzling Day in the Snow]", type: "power", rarity: "SSR", limitBreak: 4, supportId: 30074 },
  { name: "Marvelous Sunday [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10043 },
  { name: "Matikanefukukitaru [Fate's Forecast]", type: "wisdom", rarity: "SR", limitBreak: 4, supportId: 20016 },
  { name: "Matikanefukukitaru [Touching Sleeves Is Good Luck! \u266a]", type: "speed", rarity: "SSR", limitBreak: 1, supportId: 30078 },
  { name: "Matikanefukukitaru [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10044 },
  { name: "Matikanetannhauser [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10057 },
  { name: "Mayano Top Gun [Cute + Cute = ?]", type: "stamina", rarity: "SR", limitBreak: 4, supportId: 20007 },
  { name: "Mayano Top Gun [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10030 },
  { name: "Meisho Doto [Fighting for Fortune]", type: "guts", rarity: "SR", limitBreak: 4, supportId: 20017 },
  { name: "Meisho Doto [Leaping into the Unknown]", type: "stamina", rarity: "SSR", limitBreak: 3, supportId: 30079 },
  { name: "Meisho Doto [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10045 },
  { name: "Mejiro Ardan [My Heart Will Go On]", type: "wisdom", rarity: "SR", limitBreak: 4, supportId: 20034 },
  { name: "Mejiro Ardan [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10069 },
  { name: "Mejiro Bright [Little by Little]", type: "stamina", rarity: "SSR", limitBreak: 4, supportId: 30087 },
  { name: "Mejiro Bright [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10076 },
  { name: "Mejiro Dober [Ignore the Stares]", type: "wisdom", rarity: "SR", limitBreak: 4, supportId: 20018 },
  { name: "Mejiro Dober [My Thoughts, My Desires]", type: "wisdom", rarity: "SSR", limitBreak: 3, supportId: 30041 },
  { name: "Mejiro Dober [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10046 },
  { name: "Mejiro McQueen [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10010 },
  { name: "Mejiro McQueen [Your Team Ace]", type: "stamina", rarity: "SSR", limitBreak: 2, supportId: 30022 },
  { name: "Mejiro Palmer [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10054 },
  { name: "Mejiro Ryan [Hot Hearts and Cool Drinks]", type: "stamina", rarity: "SR", limitBreak: 3, supportId: 20040 },
  { name: "Mejiro Ryan [On and Off the Court]", type: "power", rarity: "SR", limitBreak: 4, supportId: 20010 },
  { name: "Mejiro Ryan [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10033 },
  { name: "Mihono Bourbon [Pal-Assisted Training]", type: "power", rarity: "SR", limitBreak: 0, supportId: 20009 },
  { name: "Mihono Bourbon [The Ghost Finds Halloween Magic]", type: "wisdom", rarity: "SSR", limitBreak: 3, supportId: 30066 },
  { name: "Mihono Bourbon [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10032 },
  { name: "Mihono Bourbon [U & Me]", type: "speed", rarity: "SSR", limitBreak: 2, supportId: 30121 },
  { name: "Mr. C.B. [Dear Mr. C.B.]", type: "wisdom", rarity: "SSR", limitBreak: 0, supportId: 30097 },
  { name: "Mr. C.B. [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10078 },
  { name: "Nakayama Festa [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10067 },
  { name: "Narita Brian [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10072 },
  { name: "Narita Brian [Two Pieces]", type: "speed", rarity: "SSR", limitBreak: 2, supportId: 30044 },
  { name: "Narita Taishin [Poolside High Tides]", type: "speed", rarity: "SR", limitBreak: 4, supportId: 20014 },
  { name: "Narita Taishin [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10040 },
  { name: "Narita Top Road [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 3, supportId: 10077 },
  { name: "Nice Nature [It's Just Water]", type: "guts", rarity: "SR", limitBreak: 4, supportId: 20019 },
  { name: "Nice Nature [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10047 },
  { name: "Nishino Flower [Even the Littlest Bud]", type: "speed", rarity: "SSR", limitBreak: 0, supportId: 30018 },
  { name: "Nishino Flower [Lifting Your Spirits]", type: "power", rarity: "SR", limitBreak: 4, supportId: 20027 },
  { name: "Nishino Flower [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10041 },
  { name: "Oguri Cap [I Love You... Dear Food]", type: "guts", rarity: "SR", limitBreak: 0, supportId: 20048 },
  { name: "Oguri Cap [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10005 },
  { name: "Rice Shower [Day I Dreamed Of]", type: "wisdom", rarity: "SSR", limitBreak: 1, supportId: 30100 },
  { name: "Rice Shower [Happiness Just around the Bend]", type: "power", rarity: "SSR", limitBreak: 1, supportId: 30034 },
  { name: "Rice Shower [Showered in Joy]", type: "stamina", rarity: "SSR", limitBreak: 2, supportId: 30023 },
  { name: "Rice Shower [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10015 },
  { name: "Riko Kashimoto [Tracen Academy]", type: "friend", rarity: "R", limitBreak: 4, supportId: 10060 },
  { name: "Sakura Bakushin O [Eat Fast! Yum Fast!]", type: "speed", rarity: "SSR", limitBreak: 1, supportId: 30015 },
  { name: "Sakura Bakushin O [The Perfect Morning Greeting!]", type: "power", rarity: "SR", limitBreak: 2, supportId: 20042 },
  { name: "Sakura Bakushin O [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10018 },
  { name: "Sakura Chiyono O [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10062 },
  { name: "Sasami Anshinzawa [Acupuncturist]", type: "friend", rarity: "R", limitBreak: 4, supportId: 10074 },
  { name: "Satono Diamond [Special Dreamers!]", type: "wisdom", rarity: "SSR", limitBreak: 4, supportId: 30088 },
  { name: "Satono Diamond [The Will to Overtake]", type: "stamina", rarity: "SSR", limitBreak: 0, supportId: 30029 },
  { name: "Satono Diamond [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10056 },
  { name: "Seeking the Pearl [The World's My Oyster]", type: "guts", rarity: "SR", limitBreak: 2, supportId: 20029 },
  { name: "Seeking the Pearl [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10061 },
  { name: "Seiun Sky [Bobbing with the Waves]", type: "wisdom", rarity: "SR", limitBreak: 1, supportId: 20050 },
  { name: "Seiun Sky [Foolproof Plan]", type: "stamina", rarity: "SSR", limitBreak: 0, supportId: 30008 },
  { name: "Seiun Sky [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10014 },
  { name: "Shinko Windy [///WARNING GATE///]", type: "speed", rarity: "SR", limitBreak: 4, supportId: 20031 },
  { name: "Shinko Windy [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10066 },
  { name: "Silence Suzuka [Searching for Unseen Sights]", type: "speed", rarity: "SSR", limitBreak: 2, supportId: 30076 },
  { name: "Silence Suzuka [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10002 },
  { name: "Silence Suzuka [Winning Dream]", type: "stamina", rarity: "SSR", limitBreak: 4, supportId: 30062 },
  { name: "Sirius Symboli [The Brightest Star Shines On]", type: "guts", rarity: "SR", limitBreak: 3, supportId: 20038 },
  { name: "Sirius Symboli [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10071 },
  { name: "Smart Falcon [Almost... an Umadol?! \u2661]", type: "guts", rarity: "SR", limitBreak: 4, supportId: 20045 },
  { name: "Smart Falcon [My Umadol Way! \u2606]", type: "power", rarity: "SSR", limitBreak: 0, supportId: 30017 },
  { name: "Smart Falcon [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10039 },
  { name: "Special Week [At the End of the Day]", type: "power", rarity: "SR", limitBreak: 4, supportId: 20043 },
  { name: "Special Week [The Brightest Star in Japan!]", type: "guts", rarity: "SSR", limitBreak: 1, supportId: 30001 },
  { name: "Special Week [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10001 },
  { name: "Super Creek [Piece of Mind]", type: "stamina", rarity: "SSR", limitBreak: 4, supportId: 30016 },
  { name: "Super Creek [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10019 },
  { name: "Sweep Tosho [Lamplit Training of a Witch-to-Be]", type: "speed", rarity: "SR", limitBreak: 4, supportId: 20023 },
  { name: "Sweep Tosho [Reckless Witch Training]", type: "wisdom", rarity: "SR", limitBreak: 1, supportId: 20046 },
  { name: "Sweep Tosho [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10050 },
  { name: "Symboli Rudolf [Tracen Academy]", type: "wisdom", rarity: "R", limitBreak: 4, supportId: 10013 },
  { name: "TM Opera O [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10012 },
  { name: "Taiki Shuttle [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10008 },
  { name: "Tamamo Cross [Beware! Halloween Night!]", type: "power", rarity: "SSR", limitBreak: 0, supportId: 30064 },
  { name: "Tamamo Cross [Split the Sky, White Lightning!]", type: "stamina", rarity: "SSR", limitBreak: 0, supportId: 30009 },
  { name: "Tamamo Cross [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10027 },
  { name: "Tazuna Hayakawa [Tracen Academy]", type: "friend", rarity: "R", limitBreak: 4, supportId: 10021 },
  { name: "Tazuna Hayakawa [Tracen Reception]", type: "friend", rarity: "SSR", limitBreak: 1, supportId: 30021 },
  { name: "Tokai Teio [Step! Smile! Wink!]", type: "stamina", rarity: "SR", limitBreak: 3, supportId: 20047 },
  { name: "Tokai Teio [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10003 },
  { name: "Tosen Jordan [My Way]", type: "speed", rarity: "SSR", limitBreak: 3, supportId: 30084 },
  { name: "Tosen Jordan [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 3, supportId: 10070 },
  { name: "Tosen Jordan [Turf as Nails]", type: "stamina", rarity: "SR", limitBreak: 4, supportId: 20035 },
  { name: "Tsurumaru Tsuyoshi [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 1, supportId: 10081 },
  { name: "Twin Turbo [Tracen Academy]", type: "speed", rarity: "R", limitBreak: 4, supportId: 10051 },
  { name: "Vodka [An Annoying Supervisor]", type: "speed", rarity: "SR", limitBreak: 2, supportId: 20039 },
  { name: "Vodka [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10007 },
  { name: "Vodka [Wild Rider]", type: "power", rarity: "SSR", limitBreak: 0, supportId: 30005 },
  { name: "Winning Ticket [Dreams Do Come True!]", type: "power", rarity: "SSR", limitBreak: 0, supportId: 30033 },
  { name: "Winning Ticket [Full-Blown Tantrum]", type: "stamina", rarity: "SSR", limitBreak: 0, supportId: 30046 },
  { name: "Winning Ticket [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10016 },
  { name: "Yaeno Muteki [Fiery Discipline]", type: "power", rarity: "SSR", limitBreak: 0, supportId: 30032 },
  { name: "Yaeno Muteki [Tracen Academy]", type: "power", rarity: "R", limitBreak: 4, supportId: 10058 },
  { name: "Yukino Bijin [City Girl 101]", type: "guts", rarity: "SR", limitBreak: 4, supportId: 20011 },
  { name: "Yukino Bijin [Dancing Light into the Night]", type: "guts", rarity: "SSR", limitBreak: 3, supportId: 30070 },
  { name: "Yukino Bijin [Hometown Cheers]", type: "wisdom", rarity: "SSR", limitBreak: 0, supportId: 30031 },
  { name: "Yukino Bijin [Tracen Academy]", type: "guts", rarity: "R", limitBreak: 4, supportId: 10034 },
  { name: "Zenno Rob Roy [The Perfect Book for You]", type: "stamina", rarity: "SR", limitBreak: 4, supportId: 20028 },
  { name: "Zenno Rob Roy [Tracen Academy]", type: "stamina", rarity: "R", limitBreak: 4, supportId: 10059 },
]

export function buildSeedCards() {
  return SEED_CARDS.map((c) => ({ id: makeId(), ...c }))
}
